-- database/schema.sql
-- GENERATED FILE — do not edit. Regenerate with:
--     python -m database.migrations --snapshot
-- The authoritative schema is the ordered set of files in database/migrations/.
-- Snapshot of schema version 0003.

-- ===== 0001_initial_schema.sql =====

-- 0001_initial_schema.sql
-- Baseline PostgreSQL / TimescaleDB schema for the NQ Trading Pipeline.
--
-- This is the SQLite store at its final version (0003, the day-partitioned store)
-- restated for Postgres. Data from an existing SQLite file is carried over with
-- python -m database.migrate_from_sqlite.
--
--   session_days : one row per (contract, interval, price_type, NY trading day).
--                  The authoritative ledger of *which days we hold*. The collector
--                  queries it before contacting IB so that a stored day is never
--                  downloaded again. A day with no data at the source is recorded
--                  too (status 'EMPTY').
--
--   bars         : a TimescaleDB hypertable chunked on timestamp_utc. Every bar is
--                  a child of its session_days row (FK, ON DELETE CASCADE), so a bar
--                  cannot exist outside a registered day and deleting a day removes
--                  its bars atomically.

CREATE EXTENSION IF NOT EXISTS timescaledb;

CREATE TABLE contracts (
    contract_id BIGINT PRIMARY KEY,
    symbol      TEXT NOT NULL,
    expiry      TEXT,
    sec_type    TEXT NOT NULL DEFAULT 'FUT',
    exchange    TEXT NOT NULL,
    currency    TEXT NOT NULL DEFAULT 'USD',
    tick_size   DOUBLE PRECISION,
    multiplier  TEXT
);

CREATE TABLE session_days (
    contract_id        BIGINT NOT NULL REFERENCES contracts (contract_id) ON DELETE CASCADE,
    interval           TEXT NOT NULL,
    price_type         TEXT NOT NULL,
    trading_day        DATE NOT NULL,              -- NY session date
    status             TEXT NOT NULL,              -- COMPLETE | PARTIAL | EMPTY
    bar_count          INTEGER NOT NULL DEFAULT 0,
    rth_bar_count      INTEGER NOT NULL DEFAULT 0,
    open_bar_count     INTEGER NOT NULL DEFAULT 0, -- bars still flagged is_completed = 0
    expected_bar_count INTEGER,                    -- rough yardstick used to judge completeness
    first_bar_utc      TIMESTAMPTZ,
    last_bar_utc       TIMESTAMPTZ,
    source             TEXT NOT NULL DEFAULT 'IBKR',
    fetched_at         TIMESTAMPTZ NOT NULL,       -- when this day was last written
    PRIMARY KEY (contract_id, interval, price_type, trading_day),
    CHECK (status IN ('COMPLETE', 'PARTIAL', 'EMPTY'))
);

CREATE INDEX idx_session_days_day ON session_days (trading_day);
CREATE INDEX idx_session_days_status ON session_days (contract_id, interval, status);

CREATE TABLE bars (
    contract_id   BIGINT NOT NULL REFERENCES contracts (contract_id) ON DELETE CASCADE,
    interval      TEXT NOT NULL,
    price_type    TEXT NOT NULL,
    trading_day   DATE NOT NULL,                   -- NY session date
    timestamp_utc TIMESTAMPTZ NOT NULL,            -- hypertable time dimension
    session_scope TEXT NOT NULL,                   -- derived from timestamp: RTH | ETH
    open          DOUBLE PRECISION NOT NULL,
    high          DOUBLE PRECISION NOT NULL,
    low           DOUBLE PRECISION NOT NULL,
    close         DOUBLE PRECISION NOT NULL,
    volume        BIGINT NOT NULL,
    wap           DOUBLE PRECISION,
    bar_count     INTEGER,
    source        TEXT NOT NULL DEFAULT 'IBKR',
    is_completed  SMALLINT NOT NULL DEFAULT 1,
    PRIMARY KEY (contract_id, interval, price_type, trading_day, timestamp_utc),
    FOREIGN KEY (contract_id, interval, price_type, trading_day)
        REFERENCES session_days (contract_id, interval, price_type, trading_day)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CHECK (session_scope IN ('RTH', 'ETH')),
    CHECK (is_completed IN (0, 1))
);

-- 30-day chunks: a month of one-minute NQ bars is ~30k rows (~5 MB per contract),
-- so chunks stay small enough to live in memory while a multi-year history is still
-- only a few dozen chunks to plan over. Queries bound timestamp_utc so all other
-- chunks are excluded. Also creates the timestamp_utc index for range scans.
SELECT create_hypertable('bars', by_range('timestamp_utc', INTERVAL '30 days'));

CREATE TABLE collection_runs (
    run_id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id            BIGINT NOT NULL REFERENCES contracts (contract_id) ON DELETE CASCADE,
    trading_day            DATE,
    interval               TEXT,
    requested_start_utc    TIMESTAMPTZ NOT NULL,
    requested_end_utc      TIMESTAMPTZ NOT NULL,
    download_status        TEXT NOT NULL,
    errors                 TEXT,
    missing_intervals      JSONB,
    bars_written           INTEGER,
    last_successful_update TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_collection_runs_day ON collection_runs (contract_id, trading_day);

CREATE TABLE feature_snapshots (
    snapshot_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id           BIGINT NOT NULL REFERENCES contracts (contract_id) ON DELETE CASCADE,
    timestamp_utc         TIMESTAMPTZ NOT NULL,
    previous_rth_high     DOUBLE PRECISION,
    previous_rth_low      DOUBLE PRECISION,
    previous_rth_close    DOUBLE PRECISION,
    overnight_high        DOUBLE PRECISION,
    overnight_low         DOUBLE PRECISION,
    overnight_range       DOUBLE PRECISION,
    gap                   DOUBLE PRECISION,
    pre_open_direction    TEXT,
    historical_volatility DOUBLE PRECISION,
    vwap                  DOUBLE PRECISION,
    raw_features          JSONB,
    feature_version       TEXT NOT NULL,
    data_quality_status   TEXT NOT NULL,
    UNIQUE (contract_id, timestamp_utc, feature_version)
);

CREATE INDEX idx_features_timestamp ON feature_snapshots (timestamp_utc);

CREATE TABLE predictions (
    prediction_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id     BIGINT NOT NULL REFERENCES contracts (contract_id) ON DELETE CASCADE,
    forecast_cutoff TIMESTAMPTZ NOT NULL,
    snapshot_id     BIGINT NOT NULL REFERENCES feature_snapshots (snapshot_id),
    model_version   TEXT NOT NULL,
    prompt_version  TEXT NOT NULL,
    opening_bias    TEXT,
    scenarios       JSONB,
    probabilities   JSONB,
    raw_response    TEXT,
    created_at      TIMESTAMPTZ NOT NULL
);

CREATE TABLE outcomes (
    outcome_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id           BIGINT NOT NULL REFERENCES contracts (contract_id) ON DELETE CASCADE,
    session_date          DATE NOT NULL,
    first_15_minute_high  DOUBLE PRECISION,
    first_15_minute_low   DOUBLE PRECISION,
    first_15_minute_close DOUBLE PRECISION,
    first_30_minute_high  DOUBLE PRECISION,
    first_30_minute_low   DOUBLE PRECISION,
    first_30_minute_close DOUBLE PRECISION,
    initial_balance_high  DOUBLE PRECISION,
    initial_balance_low   DOUBLE PRECISION,
    rth_high              DOUBLE PRECISION,
    rth_low               DOUBLE PRECISION,
    rth_close             DOUBLE PRECISION,
    raw_outcomes          JSONB,
    UNIQUE (contract_id, session_date)
);

CREATE TABLE analogue_matches (
    match_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prediction_id    BIGINT NOT NULL REFERENCES predictions (prediction_id) ON DELETE CASCADE,
    match_date       DATE NOT NULL,
    similarity_score DOUBLE PRECISION NOT NULL,
    ranking          INTEGER NOT NULL,
    UNIQUE (prediction_id, match_date)
);

-- ===== 0002_vix_pre_open_context.sql =====

-- 0002_vix_pre_open_context.sql
-- Records the cash VIX level as it stood at the 09:30 ET feature cutoff, as
-- pre-open context for the equity-index forecasts.
--
-- VIX is collected like any other instrument (its own contracts row, sec_type
-- 'IND', NULL expiry) but is never a forecast target, so these columns live on
-- the futures' snapshots rather than getting their own table.
--
-- Both are nullable: snapshots computed before VIX was collected, or for a day
-- with no VIX bars, simply leave them NULL rather than reporting a wrong level.

ALTER TABLE feature_snapshots
    ADD COLUMN IF NOT EXISTS vix_pre_open DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS vix_change   DOUBLE PRECISION;

COMMENT ON COLUMN feature_snapshots.vix_pre_open IS
    'Last cash VIX print strictly before 09:30 ET on the target trading day.';
COMMENT ON COLUMN feature_snapshots.vix_change IS
    'vix_pre_open minus the previous session''s closing VIX, in index points.';

-- ===== 0003_intermarket_sources.sql =====

-- 0003_intermarket_sources.sql
-- Prepares the store for the pre-open intermarket features (NQ/ES/RTY returns,
-- VIX/VXN levels, yields, the dollar, semiconductors).
--
-- Those features pair two observations of the *same* instrument: its latest
-- eligible pre-open value and its value at/before the previous NQ RTH close. That
-- needs three things the store did not record:
--
--   contracts        : what IB says about each contract - its contract month (the
--                      roll needs it; for CL it differs from the expiry month), and
--                      the trading/liquid hours and time zone that bound when a
--                      genuine observation can exist at all.
--
--   active_contracts : which contract stood for a symbol on each trading day. The
--                      collector fills it from the instrument's roll rule; a
--                      feature reads its contract here instead of guessing, so a
--                      return never mixes two expiries. The collector also stores
--                      the trading day *before* a contract becomes active, so the
--                      first day after a roll still has a same-contract reference.
--
--   asset_sources    : every version of the logical-asset -> instrument map
--                      (config.ASSET_SOURCES), with units, proxy flags and the
--                      freshness rule, so a feature row can always be traced to
--                      the exact source definition it was built under.

ALTER TABLE contracts
    ADD COLUMN IF NOT EXISTS contract_month   TEXT,        -- 'YYYYMM', futures only
    ADD COLUMN IF NOT EXISTS local_symbol     TEXT,
    ADD COLUMN IF NOT EXISTS trading_class    TEXT,
    ADD COLUMN IF NOT EXISTS primary_exchange TEXT,
    ADD COLUMN IF NOT EXISTS time_zone_id     TEXT,
    ADD COLUMN IF NOT EXISTS trading_hours    TEXT,        -- IB tradingHours, as sent
    ADD COLUMN IF NOT EXISTS liquid_hours     TEXT,        -- IB liquidHours, as sent
    ADD COLUMN IF NOT EXISTS updated_at       TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_contracts_symbol ON contracts (symbol, expiry);

CREATE TABLE active_contracts (
    symbol      TEXT NOT NULL,
    trading_day DATE NOT NULL,                   -- NY session date
    contract_id BIGINT NOT NULL REFERENCES contracts (contract_id) ON DELETE CASCADE,
    rule        TEXT NOT NULL,                   -- how it was chosen, e.g. the roll rule
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (symbol, trading_day)
);

CREATE INDEX idx_active_contracts_contract ON active_contracts (contract_id, trading_day);

CREATE TABLE asset_sources (
    asset               TEXT NOT NULL,           -- logical asset: nq, es, vix, us10y, ...
    config_hash         TEXT NOT NULL,           -- hash of every field below
    symbol              TEXT,                    -- NULL: no recorded source, features are null
    sec_type            TEXT,
    exchange            TEXT,
    what_to_show        TEXT,                    -- IB whatToShow = bars.price_type
    value_kind          TEXT,                    -- price | index_level | yield
    value_unit          TEXT,                    -- price | index_points | percent | percent_x10 | decimal
    bps_per_unit        DOUBLE PRECISION,        -- yields: bps = (now - ref) * bps_per_unit
    max_age_minutes     INTEGER,                 -- freshness rule for both endpoints
    roll_rule           TEXT,
    is_proxy            BOOLEAN NOT NULL DEFAULT false,
    optional            BOOLEAN NOT NULL DEFAULT false,
    collected           BOOLEAN NOT NULL,        -- was the symbol in the collector's set
    description         TEXT,
    notes               TEXT,
    first_registered_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_registered_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (asset, config_hash),
    CHECK (value_kind IS NULL OR value_kind IN ('price', 'index_level', 'yield')),
    CHECK (value_unit IS NULL OR value_unit IN ('price', 'index_points', 'percent', 'percent_x10', 'decimal'))
);

-- The definition each asset is currently collected under.
CREATE VIEW current_asset_sources AS
SELECT DISTINCT ON (asset) *
  FROM asset_sources
 ORDER BY asset, last_registered_at DESC;

COMMENT ON COLUMN bars.timestamp_utc IS
    'Bar OPEN time in UTC (IB convention). A 1-minute bar stamped 09:27 ET closes at 09:28 ET, '
    'so the "09:28 close" is the close of the bar stamped 09:27.';
COMMENT ON COLUMN bars.volume IS
    'Traded volume; 0 for a cash index, which IB reports without volume.';
COMMENT ON TABLE bars IS
    'Only bars the source actually sent. Minutes without a print are absent, never '
    'forward-filled, so the age of the latest value is always recoverable.';
