-- 0001_initial_schema.sql
-- Baseline PostgreSQL / TimescaleDB schema for the NQ Trading Pipeline.
--
-- This is the SQLite store at its final version (0003, the day-partitioned store)
-- restated for Postgres. Data from an existing SQLite file is carried over with
-- python -m database.migrate_from_sqlite.
--
--   session_days : one row per (contract, interval, price_type, NY trading day).
--                  The authoritative ledger of *which days we hold*. The collector
--                  queries it before contacting IB so that a stored day is never
--                  downloaded again. A day with no data at the source is recorded
--                  too (status 'EMPTY').
--
--   bars         : a TimescaleDB hypertable chunked on timestamp_utc. Every bar is
--                  a child of its session_days row (FK, ON DELETE CASCADE), so a bar
--                  cannot exist outside a registered day and deleting a day removes
--                  its bars atomically.

CREATE EXTENSION IF NOT EXISTS timescaledb;

CREATE TABLE contracts (
    contract_id BIGINT PRIMARY KEY,
    symbol      TEXT NOT NULL,
    expiry      TEXT,
    sec_type    TEXT NOT NULL DEFAULT 'FUT',
    exchange    TEXT NOT NULL,
    currency    TEXT NOT NULL DEFAULT 'USD',
    tick_size   DOUBLE PRECISION,
    multiplier  TEXT
);

CREATE TABLE session_days (
    contract_id        BIGINT NOT NULL REFERENCES contracts (contract_id) ON DELETE CASCADE,
    interval           TEXT NOT NULL,
    price_type         TEXT NOT NULL,
    trading_day        DATE NOT NULL,              -- NY session date
    status             TEXT NOT NULL,              -- COMPLETE | PARTIAL | EMPTY
    bar_count          INTEGER NOT NULL DEFAULT 0,
    rth_bar_count      INTEGER NOT NULL DEFAULT 0,
    open_bar_count     INTEGER NOT NULL DEFAULT 0, -- bars still flagged is_completed = 0
    expected_bar_count INTEGER,                    -- rough yardstick used to judge completeness
    first_bar_utc      TIMESTAMPTZ,
    last_bar_utc       TIMESTAMPTZ,
    source             TEXT NOT NULL DEFAULT 'IBKR',
    fetched_at         TIMESTAMPTZ NOT NULL,       -- when this day was last written
    PRIMARY KEY (contract_id, interval, price_type, trading_day),
    CHECK (status IN ('COMPLETE', 'PARTIAL', 'EMPTY'))
);

CREATE INDEX idx_session_days_day ON session_days (trading_day);
CREATE INDEX idx_session_days_status ON session_days (contract_id, interval, status);

CREATE TABLE bars (
    contract_id   BIGINT NOT NULL REFERENCES contracts (contract_id) ON DELETE CASCADE,
    interval      TEXT NOT NULL,
    price_type    TEXT NOT NULL,
    trading_day   DATE NOT NULL,                   -- NY session date
    timestamp_utc TIMESTAMPTZ NOT NULL,            -- hypertable time dimension
    session_scope TEXT NOT NULL,                   -- derived from timestamp: RTH | ETH
    open          DOUBLE PRECISION NOT NULL,
    high          DOUBLE PRECISION NOT NULL,
    low           DOUBLE PRECISION NOT NULL,
    close         DOUBLE PRECISION NOT NULL,
    volume        BIGINT NOT NULL,
    wap           DOUBLE PRECISION,
    bar_count     INTEGER,
    source        TEXT NOT NULL DEFAULT 'IBKR',
    is_completed  SMALLINT NOT NULL DEFAULT 1,
    PRIMARY KEY (contract_id, interval, price_type, trading_day, timestamp_utc),
    FOREIGN KEY (contract_id, interval, price_type, trading_day)
        REFERENCES session_days (contract_id, interval, price_type, trading_day)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CHECK (session_scope IN ('RTH', 'ETH')),
    CHECK (is_completed IN (0, 1))
);

-- One chunk per week of bars: ~6.5k one-minute NQ bars per contract, small enough
-- that a day's delete-and-replace touches a single chunk. Also creates the
-- timestamp_utc index that cross-day range queries use.
SELECT create_hypertable('bars', by_range('timestamp_utc', INTERVAL '7 days'));

CREATE TABLE collection_runs (
    run_id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id            BIGINT NOT NULL REFERENCES contracts (contract_id) ON DELETE CASCADE,
    trading_day            DATE,
    interval               TEXT,
    requested_start_utc    TIMESTAMPTZ NOT NULL,
    requested_end_utc      TIMESTAMPTZ NOT NULL,
    download_status        TEXT NOT NULL,
    errors                 TEXT,
    missing_intervals      JSONB,
    bars_written           INTEGER,
    last_successful_update TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_collection_runs_day ON collection_runs (contract_id, trading_day);

CREATE TABLE feature_snapshots (
    snapshot_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id           BIGINT NOT NULL REFERENCES contracts (contract_id) ON DELETE CASCADE,
    timestamp_utc         TIMESTAMPTZ NOT NULL,
    previous_rth_high     DOUBLE PRECISION,
    previous_rth_low      DOUBLE PRECISION,
    previous_rth_close    DOUBLE PRECISION,
    overnight_high        DOUBLE PRECISION,
    overnight_low         DOUBLE PRECISION,
    overnight_range       DOUBLE PRECISION,
    gap                   DOUBLE PRECISION,
    pre_open_direction    TEXT,
    historical_volatility DOUBLE PRECISION,
    vwap                  DOUBLE PRECISION,
    raw_features          JSONB,
    feature_version       TEXT NOT NULL,
    data_quality_status   TEXT NOT NULL,
    UNIQUE (contract_id, timestamp_utc, feature_version)
);

CREATE INDEX idx_features_timestamp ON feature_snapshots (timestamp_utc);

CREATE TABLE predictions (
    prediction_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id     BIGINT NOT NULL REFERENCES contracts (contract_id) ON DELETE CASCADE,
    forecast_cutoff TIMESTAMPTZ NOT NULL,
    snapshot_id     BIGINT NOT NULL REFERENCES feature_snapshots (snapshot_id),
    model_version   TEXT NOT NULL,
    prompt_version  TEXT NOT NULL,
    opening_bias    TEXT,
    scenarios       JSONB,
    probabilities   JSONB,
    raw_response    TEXT,
    created_at      TIMESTAMPTZ NOT NULL
);

CREATE TABLE outcomes (
    outcome_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id           BIGINT NOT NULL REFERENCES contracts (contract_id) ON DELETE CASCADE,
    session_date          DATE NOT NULL,
    first_15_minute_high  DOUBLE PRECISION,
    first_15_minute_low   DOUBLE PRECISION,
    first_15_minute_close DOUBLE PRECISION,
    first_30_minute_high  DOUBLE PRECISION,
    first_30_minute_low   DOUBLE PRECISION,
    first_30_minute_close DOUBLE PRECISION,
    initial_balance_high  DOUBLE PRECISION,
    initial_balance_low   DOUBLE PRECISION,
    rth_high              DOUBLE PRECISION,
    rth_low               DOUBLE PRECISION,
    rth_close             DOUBLE PRECISION,
    raw_outcomes          JSONB,
    UNIQUE (contract_id, session_date)
);

CREATE TABLE analogue_matches (
    match_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prediction_id    BIGINT NOT NULL REFERENCES predictions (prediction_id) ON DELETE CASCADE,
    match_date       DATE NOT NULL,
    similarity_score DOUBLE PRECISION NOT NULL,
    ranking          INTEGER NOT NULL,
    UNIQUE (prediction_id, match_date)
);
